export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const TERIMA_PESANAN = 'TERIMA_PESANAN';
export const TERIMA_PESANAN_SUCCESS = 'TERIMA_PESANAN_SUCCESS';
export const TERIMA_PESANAN_FAILED = 'TERIMA_PESANAN_FAILED';

export const SELESAIKAN_PESANAN = 'SELESAIKAN_PESANAN';
export const SELESAIKAN_PESANAN_SUCCESS = 'SELESAIKAN_PESANAN_SUCCESS';
export const SELESAIKAN_PESANAN_FAILED = 'SELESAIKAN_PESANAN_FAILED';

export const TOGGLE_AKTIF = 'TOGGLE_AKTIF';

export const GO_TO_PELANGGAN = 'GO_TO_PELANGGAN';

export const ON_ADA_PESAN = 'ON_ADA_PESAN';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export default TERIMA_PESANAN;
