export const CHANGE_SCREEN = 'CHANGE_SCREEN'


export const SELESAIKAN_PESANAN = 'SELESAIKAN_PESANAN'
export const SELESAIKAN_PESANAN_SUKSES = 'SELESAIKAN_PESANAN_SUKSES'
export const SELESAIKAN_PESANAN_GAGAL  = 'SELESAIKAN_PESANAN_GAGAL'
